// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMixOQkt0aUOyCGUNTGLJ9SlBYvjU4HEE',
    appId: '1:386290065135:web:174dfed17d15858720051a',
    messagingSenderId: '386290065135',
    projectId: 'auth-example-406d6',
    authDomain: 'auth-example-406d6.firebaseapp.com',
    storageBucket: 'auth-example-406d6.appspot.com',
    measurementId: 'G-4S4BP2DNPG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqzvtJUqlG2mW617XLeqcGVFhwZlwag-0',
    appId: '1:386290065135:android:44fbc31d7e4f7a5020051a',
    messagingSenderId: '386290065135',
    projectId: 'auth-example-406d6',
    storageBucket: 'auth-example-406d6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC99IcYUdYp-SxkihZv6rNMP5khv3wTAmw',
    appId: '1:386290065135:ios:df499a2ced096e7520051a',
    messagingSenderId: '386290065135',
    projectId: 'auth-example-406d6',
    storageBucket: 'auth-example-406d6.appspot.com',
    iosBundleId: 'com.example.authExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC99IcYUdYp-SxkihZv6rNMP5khv3wTAmw',
    appId: '1:386290065135:ios:7ef10a0dd4defb9a20051a',
    messagingSenderId: '386290065135',
    projectId: 'auth-example-406d6',
    storageBucket: 'auth-example-406d6.appspot.com',
    iosBundleId: 'com.example.authExample.RunnerTests',
  );
}
